groups:
- name: main
  jobs:
  - test-master
  - test-pr
  - build
  # - deploy

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: code-base
  type: git
  source:
    uri: https://github.com/translationCoreApps/word-map
    branch: master
- name: concourse-tasks
  type: git
  source:
    uri: https://github.com/neutrinog/concourse-tasks
    branch: map
- name: git-pull-request
  type: pull-request
  source:
    repo: translationCoreApps/word-map
    access_token: ((github-token))

jobs:
- name: test-pr
  public: true
  plan:
  - get: git-pull-request
    trigger: true
  - get: concourse-tasks
  - task: test-pull-request
    input_mapping:
      code-base: git-pull-request
    file: concourse-tasks/tasks/unit-tests.yml
- name: test-master
  public: true
  plan:
  - get: concourse-tasks
  - get: code-base
    trigger: true
  - task: run-unit-tests
    file: concourse-tasks/tasks/unit-tests.yml
- name: build
  public: true
  plan:
  - get: code-base
    trigger: true
    passed:
      - test-master
  - get: git-pull-request
    trigger: true
    passed:
      - test-pr
  - get: concourse-tasks
  - task: build-linux
    file: concourse-tasks/tasks/build.yml
  - task: zip-it
    file: concourse-tasks/tasks/zip.yml
  - task: release-it
    file: concourse-tasks/tasks/surge.yml
# - name: deploy
#   public: true
#   plan:
#   - get: code-base
#     trigger: true
#     passed:
#       - builds
#   - get: concourse-tasks
#     trigger: true
#     passed:
#       - builds
#   - task: zip-it
#     file: concourse-tasks/tasks/zip.yml
#  - task: surge-it
#    file: concourse-tasks/tasks/surge.yml
