groups:
- name: main
  jobs:
  - Test Develop
  - Test PR
  - Build Develop

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: develop-branch
  type: git
  source:
    uri: https://github.com/unfoldingWord-dev/translationCore
    branch: develop
- name: concourse-tasks
  type: git
  source:
    uri: https://github.com/neutrinog/concourse-tasks
    branch: master
- name: develop-pull-requests
  type: pull-request
  source:
    access_token: ((github-token))
    private_key: ((github-private-key))
    repo: unfoldingWord-dev/translationCore
    base: develop
- name: builds
  type: s3
  source:
    bucket: tc-builds.door43.org
    regexp: translationCore-(.*)-(.*)-(?<version>.*)\.(.*)
    access_key_id: ((aws-access-id))
    secret_access_key: ((aws-secret-key))
    region_name: us-west-2

jobs:
# test pull requests
- name: Test PR
  public: true
  plan:
  - get: develop-pull-requests
    trigger: true
    version: every
  - get: concourse-tasks
  - task: show-pending
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      run:
        path: echo
        args: [setting pending status]
    on_success:
      put: develop-pull-requests
      params:
        path: develop-pull-requests
        context: unit-tests
        status: pending
  - task: test-pull-request
    input_mapping:
      code-base: develop-pull-requests
    file: concourse-tasks/tasks/unit-tests.yml
    on_success:
      put: develop-pull-requests
      params:
        path: develop-pull-requests
        context: unit-tests
        comment: test-log/comment.md
        status: success
    on_failure:
      put: develop-pull-requests
      params:
        path: develop-pull-requests
        context: unit-tests
        status: failure

# test develop branch
- name: Test Develop
  public: true
  plan:
  - get: concourse-tasks
  - get: develop-branch
    trigger: true
  - task: run-unit-tests
    input_mapping:
      code-base: develop-branch
    file: concourse-tasks/tasks/unit-tests.yml

# build develop branch
- name: Build Develop
  public: true
  plan:
  - get: code-base
    resource: develop-branch
    trigger: true
    passed:
      - Test Develop
  - get: concourse-tasks
  - task: build-linux
    file: concourse-tasks/tasks/build-linux.yml
    on_success:
      put: builds
      params:
        file: build/linux-x64/*
        acl: public-read
