groups:
- name: main
  jobs:
  - unit-tests
  - builds

resources:
- name: code-base
  type: git
  source:
    uri: https://github.com/neutrinog/translationCore
    branch: develop
- name: concourse-tasks
  type: git
  source:
    uri: https://github.com/neutrinog/concourse-tasks
    branch: master

jobs:
- name: unit-tests
  public: true
  plan:
  - get: concourse-tasks
    trigger: true
  - get: code-base
    trigger: true
  - task: run-unit-tests
    file: concourse-tasks/tasks/unit-tests.yml
- name: builds
  public: true
  plan:
  - get: code-base
    trigger: true
    passed:
      - unit-tests
  - get: concourse-tasks
    trigger: true
    passed:
      - unit-tests
  - task: build-linux
    file: concourse-tasks/tasks/build.yml
