groups:
- name: main
  jobs:
  - unit-tests
  - builds
  - deploy

resources:
- name: code-base
  type: git
  source:
    uri: https://github.com/translationCoreApps/word-map
    branch: master
- name: concourse-tasks
  type: git
  source:
    uri: https://github.com/neutrinog/concourse-tasks
    branch: map

jobs:
- name: unit-tests
  public: true
  plan:
  - get: concourse-tasks
    trigger: true
  - get: code-base
    trigger: true
  - task: run-unit-tests
    file: concourse-tasks/tasks/unit-tests.yml
- name: builds
  public: true
  plan:
  - get: code-base
    trigger: true
    passed:
      - unit-tests
  - get: concourse-tasks
    trigger: true
    passed:
      - unit-tests
  - task: build-linux
    file: concourse-tasks/tasks/build.yml
- name: deploy
  public: true
  plan:
  - get: code-base
    trigger: true
    passed:
      - builds
  - get: concourse-tasks
    trigger: true
    passed:
      - builds
  - task: zip-it
    file: concourse-tasks/tasks/zip.yml
#  - task: surge-it
#    file: concourse-tasks/tasks/surge.yml
