groups:
- name: main
  jobs:
  - test-master
  - PR tests
  - build
  # - deploy

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: code-base
  type: git
  source:
    uri: https://github.com/translationCoreApps/word-map
    branch: master
- name: concourse-tasks
  type: git
  source:
    uri: https://github.com/neutrinog/concourse-tasks
    branch: map
# - name: git-pr
#   type: pull-request
#   source:
#     repo: translationCoreApps/word-map
#     access_token: ((github-token))
#
- name: git-pull-requests
  type: pull-request
  source:
    access_token: ((github-token))
    private_key: ((github-private-key))
    repo: translationCoreApps/word-map
    base: master

jobs:
- name: PR tests
  public: true
  plan:
  - get: git-pull-requests
    trigger: true
    version: every
  - get: concourse-tasks
  - task: show-pending
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      run:
        path: echo
        args: [setting pending status]
    on_success:
      put: git-pull-requests
      params:
        path: git-pull-requests
        context: unit-tests
        status: pending
  - task: test-pull-request
    input_mapping:
      code-base: git-pull-requests
    file: concourse-tasks/tasks/unit-tests.yml
    on_success:
      put: git-pull-requests
      params:
        path: git-pull-requests
        context: unit-tests
        comment: test-log/comment.md
        status: success
    on_failure:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: failure
- name: test-master
  public: true
  plan:
  - get: concourse-tasks
  - get: code-base
    trigger: true
  - task: run-unit-tests
    file: concourse-tasks/tasks/unit-tests.yml
- name: build
  public: true
  plan:
  - get: code-base
    trigger: true
    passed:
      - test-master
  - get: git-pull-requests
    trigger: true
    passed:
      - PR tests
  - get: concourse-tasks
  - task: build-linux
    file: concourse-tasks/tasks/build.yml
  - task: zip-it
    file: concourse-tasks/tasks/zip.yml
  - task: release-it
    file: concourse-tasks/tasks/dropbox.yml
    params:
      TOKEN: ((dropbox-token))
# - name: deploy
#   public: true
#   plan:
#   - get: code-base
#     trigger: true
#     passed:
#       - builds
#   - get: concourse-tasks
#     trigger: true
#     passed:
#       - builds
#   - task: zip-it
#     file: concourse-tasks/tasks/zip.yml
#  - task: surge-it
#    file: concourse-tasks/tasks/surge.yml
