
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: neutrinog/node-docker
    tag: "8.10"

inputs:
- name: concourse-tasks

outputs:
- name: build_meta

params:
  text:

run:
  path: concourse-tasks/scripts/run-add-build-comment.sh
