
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: neutrinog/concourse-tasks

inputs:
- name: concourse-tasks
- name: code-base
- name: build_meta
  path: input_meta
  optional: true

outputs:
- name: build
- name: build_meta

params:
  PLATFORM: linux

run:
  path: concourse-tasks/scripts/run-build.sh
