
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: neutrinog/concourse-tasks

inputs:
- name: concourse-tasks
- name: code-base

outputs:
- name: build
- name: build_meta

run:
  path: concourse-tasks/scripts/run-build-linux.sh
