
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: neutrinog/concourse-tasks

inputs:
- name: concourse-tasks
- name: code-base
# this will be copied to the output to propogate meta between tasks
- name: build_meta
  path: input_meta
  optional: true

outputs:
- name: build
- name: build_meta

params:
  PLATFORM: linux # default value
  TC_HELP_DESK_TOKEN:
  TC_HELP_DESK_EMAIL:

run:
  path: concourse-tasks/scripts/run-build.sh
