
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: neutrinog/node-docker
    tag: "latest"

inputs:
- name: concourse-tasks
- name: code-base

outputs:
- name: release

run:
  path: concourse-tasks/tasks/run-build.sh
