
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: neutrinog/concourse-tasks

inputs:
- name: concourse-tasks
- name: release

run:
  path: concourse-tasks/scripts/dropbox_uploader.sh
  args: [-d, -t, ((dropbox-token)), upload, release, tc-builds/dist.zip]
