
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: concourse-tasks
- name: code-base

run:
  path: concourse-tasks/tasks/run-unit-tests.sh
