---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: neutrinog/concourse-tasks

inputs:
  - name: build
outputs:
  - name: release
run:
  path: zip
  args: [-r, release/dist.zip, build]
